# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aditi/SLIM-FP/slim3a

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aditi/SLIM-FP/slim3a

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aditi/SLIM-FP/slim3a/CMakeFiles /home/aditi/SLIM-FP/slim3a/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aditi/SLIM-FP/slim3a/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slimPass

# Build rule for target.
slimPass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slimPass
.PHONY : slimPass

# fast build rule for target.
slimPass/fast:
	$(MAKE) -f CMakeFiles/slimPass.dir/build.make CMakeFiles/slimPass.dir/build
.PHONY : slimPass/fast

#=============================================================================
# Target rules for targets named slim

# Build rule for target.
slim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slim
.PHONY : slim

# fast build rule for target.
slim/fast:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/build
.PHONY : slim/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

IR.o: IR.cpp.o

.PHONY : IR.o

# target to build an object file
IR.cpp.o:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/IR.cpp.o
.PHONY : IR.cpp.o

IR.i: IR.cpp.i

.PHONY : IR.i

# target to preprocess a source file
IR.cpp.i:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/IR.cpp.i
.PHONY : IR.cpp.i

IR.s: IR.cpp.s

.PHONY : IR.s

# target to generate assembly for a file
IR.cpp.s:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/IR.cpp.s
.PHONY : IR.cpp.s

Instructions.o: Instructions.cpp.o

.PHONY : Instructions.o

# target to build an object file
Instructions.cpp.o:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/Instructions.cpp.o
.PHONY : Instructions.cpp.o

Instructions.i: Instructions.cpp.i

.PHONY : Instructions.i

# target to preprocess a source file
Instructions.cpp.i:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/Instructions.cpp.i
.PHONY : Instructions.cpp.i

Instructions.s: Instructions.cpp.s

.PHONY : Instructions.s

# target to generate assembly for a file
Instructions.cpp.s:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/Instructions.cpp.s
.PHONY : Instructions.cpp.s

Operand.o: Operand.cpp.o

.PHONY : Operand.o

# target to build an object file
Operand.cpp.o:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/Operand.cpp.o
.PHONY : Operand.cpp.o

Operand.i: Operand.cpp.i

.PHONY : Operand.i

# target to preprocess a source file
Operand.cpp.i:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/Operand.cpp.i
.PHONY : Operand.cpp.i

Operand.s: Operand.cpp.s

.PHONY : Operand.s

# target to generate assembly for a file
Operand.cpp.s:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/Operand.cpp.s
.PHONY : Operand.cpp.s

Passes/GlobalInit.o: Passes/GlobalInit.cpp.o

.PHONY : Passes/GlobalInit.o

# target to build an object file
Passes/GlobalInit.cpp.o:
	$(MAKE) -f CMakeFiles/slimPass.dir/build.make CMakeFiles/slimPass.dir/Passes/GlobalInit.cpp.o
.PHONY : Passes/GlobalInit.cpp.o

Passes/GlobalInit.i: Passes/GlobalInit.cpp.i

.PHONY : Passes/GlobalInit.i

# target to preprocess a source file
Passes/GlobalInit.cpp.i:
	$(MAKE) -f CMakeFiles/slimPass.dir/build.make CMakeFiles/slimPass.dir/Passes/GlobalInit.cpp.i
.PHONY : Passes/GlobalInit.cpp.i

Passes/GlobalInit.s: Passes/GlobalInit.cpp.s

.PHONY : Passes/GlobalInit.s

# target to generate assembly for a file
Passes/GlobalInit.cpp.s:
	$(MAKE) -f CMakeFiles/slimPass.dir/build.make CMakeFiles/slimPass.dir/Passes/GlobalInit.cpp.s
.PHONY : Passes/GlobalInit.cpp.s

SLIMDebug.o: SLIMDebug.cpp.o

.PHONY : SLIMDebug.o

# target to build an object file
SLIMDebug.cpp.o:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/SLIMDebug.cpp.o
.PHONY : SLIMDebug.cpp.o

SLIMDebug.i: SLIMDebug.cpp.i

.PHONY : SLIMDebug.i

# target to preprocess a source file
SLIMDebug.cpp.i:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/SLIMDebug.cpp.i
.PHONY : SLIMDebug.cpp.i

SLIMDebug.s: SLIMDebug.cpp.s

.PHONY : SLIMDebug.s

# target to generate assembly for a file
SLIMDebug.cpp.s:
	$(MAKE) -f CMakeFiles/slim.dir/build.make CMakeFiles/slim.dir/SLIMDebug.cpp.s
.PHONY : SLIMDebug.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... slimPass"
	@echo "... slim"
	@echo "... acc_gen"
	@echo "... edit_cache"
	@echo "... omp_gen"
	@echo "... install/strip"
	@echo "... intrinsics_gen"
	@echo "... IR.o"
	@echo "... IR.i"
	@echo "... IR.s"
	@echo "... Instructions.o"
	@echo "... Instructions.i"
	@echo "... Instructions.s"
	@echo "... Operand.o"
	@echo "... Operand.i"
	@echo "... Operand.s"
	@echo "... Passes/GlobalInit.o"
	@echo "... Passes/GlobalInit.i"
	@echo "... Passes/GlobalInit.s"
	@echo "... SLIMDebug.o"
	@echo "... SLIMDebug.i"
	@echo "... SLIMDebug.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

